services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ENCAR.COM_TG-BOT
    env_file:
      - .env
    ports:
      - "8082:8080"
    depends_on:
      - selenium-standalone-chromium
    networks:
      - encar-com-tg-bot

  selenium-standalone-chromium:
    image: selenium/standalone-chromium:latest
    container_name: selenium-standalone-chromium
    ports:
      - "4444:4444"
    networks:
      - encar-com-tg-bot

networks:
  encar-com-tg-bot:
    driver: bridge
